"""Slice 11-12 -- render every hand-checkable number in the docs from source,
between the generated-numbers markers, and verify no doc has drifted.

Sources (this script INVENTS no numbers):
  * results/final_run.json            (STEP 1, full 2,000-event run, locked 70:30)
  * results/split_comparison_500.json (STEP 2, first-500-customer split sweep)
  * the pytest collection count        (`pytest --collect-only -q`)

Covered docs:
  * README.md       -- the headline corpus table + sensitivity sweep
  * EVALUATION.md   -- the quotable verdict sentence + the evidence table
  * ARCHITECTURE.md -- the structural counts (events -> customers -> decisions,
                       guardrail-evaluation rows, test count)

Every value is read straight from those sources and formatted with fixed
precision so the output is byte-stable.

Modes
-----
  python scripts/render_readme_numbers.py            # --check (default)
  python scripts/render_readme_numbers.py --check    # exit 1 if any doc drifted
  python scripts/render_readme_numbers.py --write     # splice fresh blocks in

CI runs `--check`: it re-derives each block from source and fails the build if
what is committed between the markers differs by a single byte. Regenerate with
`--write` and commit the docs alongside the artifacts.
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
README = REPO / "README.md"
EVALUATION = REPO / "EVALUATION.md"
ARCHITECTURE = REPO / "ARCHITECTURE.md"
FINAL = REPO / "results" / "final_run.json"
SPLIT = REPO / "results" / "split_comparison_500.json"

BEGIN = "<!-- BEGIN GENERATED NUMBERS -->"
END = "<!-- END GENERATED NUMBERS -->"


# ------------------------------------------------------------------ test count
def test_count() -> int:
    """The number pytest collects -- re-derived, never hard-coded. Collection
    only (no execution); ~0.4 s."""
    out = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q"],
        cwd=REPO, capture_output=True, text=True,
    )
    m = re.search(r"(\d+)\s+tests?\s+collected", out.stdout + out.stderr)
    if not m:
        raise SystemExit(
            "STOP: could not read the pytest collection count from\n"
            + (out.stdout + out.stderr)[-2000:]
        )
    return int(m.group(1))


# ------------------------------------------------------------------ formatting
def inr(x: float) -> str:
    """`479834.0` -> `479,834.00` (Indian-file uses plain thousands here)."""
    return f"{x:,.2f}"


def pp(x: float) -> str:
    """percentage-point value already in pp units -> 2 dp."""
    return f"{x:.2f}"


def pct(rate: float) -> str:
    """proportion in [0,1] -> percent, 2 dp."""
    return f"{rate * 100:.2f}"


def short_sha(h: str) -> str:
    return h[:8]


def d6(x: float) -> str:
    """6-decimal fixed -- for the uplift / CI figures quoted to full precision."""
    return f"{x:.6f}"


# ------------------------------------------------------------- README block
def render_readme_block() -> str:
    final = json.loads(FINAL.read_text(encoding="utf-8"))
    split = json.loads(SPLIT.read_text(encoding="utf-8"))

    cl = final["aggregate"]["customer_level"]
    el = final["aggregate"]["event_level"]
    agg = final["aggregate"]
    ci = cl["uplift_ci_95"]
    prov = final["provenance"]

    distinct_email = el["distinct_actions_by_rung"].get("email", 0)
    event_email = el["action_counts_by_rung"].get("email", 0)
    ev_floor_skips = el["skip_counts_by_reason"].get("EV_BELOW_FLOOR", 0)
    skip_reasons_seen = ", ".join(sorted(el["skip_counts_by_reason"])) or "none"

    sp = split["splits"]
    s70 = sp["70:30"]["customer_level"]
    s90 = sp["90:10"]["customer_level"]

    lines: list[str] = []
    add = lines.append

    add(BEGIN)
    add(
        "<!-- Generated by scripts/render_readme_numbers.py from "
        "results/final_run.json and results/split_comparison_500.json."
    )
    add("     Do not edit by hand. Regenerate: "
        "python scripts/render_readme_numbers.py --write")
    add("     CI verifies: python scripts/render_readme_numbers.py --check -->")
    add("")
    add(f"> **{final['synthetic_provenance_note']}**")
    add("")
    add("**Full corpus — "
        f"{prov['n_events']:,} events, {prov['n_customers']:,} customers, "
        "locked 70:30 split. Real `pipeline.process_failure` (guardrail "
        "walk-down included).**")
    add("")
    add("| # | Headline | Value |")
    add("|---|----------|-------|")
    add(
        f"| 1 | Incremental uplift, count basis (treatment − control recovery "
        f"rate) | **{pp(cl['incremental_uplift_pp'])} pp** "
        f"({pct(cl['recovery_rate_treatment'])}% − "
        f"{pct(cl['recovery_rate_control'])}%), "
        f"≈ {cl['incremental_recoveries_count']:.0f} extra recoveries |"
    )
    add(
        f"| 2 | 95% CI on uplift — Wilson score on the difference "
        f"(Newcombe 1998 hybrid) | "
        f"**[{pp(ci['low_pp'])}, {pp(ci['high_pp'])}] pp**, "
        f"width {pp(ci['width_pp'])} pp |"
    )
    add(
        f"| 3 | Arm sizes (customers) | "
        f"**{cl['n_treatment_customers']:,} treatment / "
        f"{cl['n_control_customers']:,} control** of {cl['n_customers']:,} "
        f"({cl['n_treatment_blocked_customers']} guardrail-blocked) |"
    )
    add(
        f"| 4 | Distinct actions (unique payment_id per rung; process_failure "
        f"is idempotent) | **{distinct_email:,} email nudges** "
        f"({event_email:,} across events); {ev_floor_skips} EV-floor skips, "
        f"{el['route_to_human_count']} routed to human, "
        f"{el['suppressed_by_guardrail_count']} guardrail-suppressed "
        f"(skip reasons seen: {skip_reasons_seen}) |"
    )
    iv_ci = cl["incremental_value_per_treated_customer_ci_95"]
    net_ci = cl["net_incremental_ev_ci_95"]
    add(
        f"| 5 | Incremental recovered value, value-weighted (treatment "
        f"recovered − control rate × treatment headcount) | "
        f"**₹{inr(cl['incremental_recovered_value_inr'])}** "
        f"(₹{inr(cl['incremental_value_per_treated_customer_inr'])} per treated "
        f"customer, 95% bootstrap [₹{inr(iv_ci['low'])}, ₹{inr(iv_ci['high'])}]) |"
    )
    add(
        f"| 6 | Net incremental EV (row 5 − ₹{inr(el['total_action_cost_inr'])} "
        f"distinct action cost) | "
        f"**₹{inr(cl['net_incremental_ev_inr'])}**, 95% bootstrap "
        f"[₹{inr(net_ci['low'])}, ₹{inr(net_ci['high'])}] |"
    )
    add("")
    if net_ci["low"] <= 0.0:
        add(
            f"**The row-6 lower bound is ₹{inr(net_ci['low'])} — at or below "
            "zero.** On this corpus the value-weighted incremental EV is not "
            "distinguishable from zero at 95% (seeded stratified bootstrap, "
            f"{net_ci['n_resamples']:,} resamples). The count-basis uplift "
            "(row 1) stays significant; the value-basis figure does not. Treat "
            "the ₹ point estimates as directional, not bankable."
        )
        add("")
    add(
        "Rows 5–6 are both on the treated-customer basis "
        f"({cl['n_treatment_customers']:,} customers); "
        f"{agg['multi_failure_customers']} customers have more than one event, "
        "which is why distinct actions (row 4) sit below the event count."
    )
    add("")
    add(f"**Count basis vs value basis.** {cl['value_vs_count_note']}")
    add("")
    add(f"**Policy selectivity.** {final['policy_selectivity_note']}")
    add("")
    add(
        "**Sensitivity — first "
        f"{split['n_customers_in_slice']} customers "
        f"({split['n_events_in_slice']} events), treatment-fraction sweep. "
        "`decide_with_ladder` direct, cross-checked against "
        "`eval.measurement.run_policy`.**"
    )
    add("")
    add("| Split | Treatment / control customers | Uplift | "
        "95% CI width (Wilson-on-difference) |")
    add("|-------|-------------------------------|--------|"
        "------------------------------------|")
    add(
        f"| 70:30 (locked) | {s70['n_treatment_customers']} / "
        f"{s70['n_control_customers']} | {pp(s70['incremental_uplift_pp'])} pp | "
        f"{pp(s70['uplift_ci_95']['width_pp'])} pp |"
    )
    add(
        f"| 90:10 | {s90['n_treatment_customers']} / "
        f"{s90['n_control_customers']} | {pp(s90['incremental_uplift_pp'])} pp | "
        f"{pp(s90['uplift_ci_95']['width_pp'])} pp |"
    )
    add("")
    add(f"Reading: {split['reading']}")
    add("")
    add(
        "Provenance (the commit that carries this artifact is the rest of it; "
        "hashes are over newline-normalized content, not raw bytes): "
        "events.json `" + short_sha(prov["sha256_events_json_normalized"]) + "`, "
        "ground_truth.json `"
        + short_sha(prov["sha256_ground_truth_json_normalized"]) + "`, "
        "decision_policy.json `"
        + short_sha(prov["sha256_decision_policy_json_normalized"]) + "`, "
        "seed " + str(prov["rng_seed"]) + ", corpus "
        + prov["corpus_time_min"] + " … " + prov["corpus_time_max"] + "."
    )
    add(END)
    return "\n".join(lines)


# --------------------------------------------------------- EVALUATION block
def render_eval_block(n_tests: int) -> str:
    final = json.loads(FINAL.read_text(encoding="utf-8"))
    cl = final["aggregate"]["customer_level"]
    el = final["aggregate"]["event_level"]
    ci = cl["uplift_ci_95"]
    net = cl["net_incremental_ev_ci_95"]
    gross = cl["incremental_recovered_value_ci_95"]
    prov = final["provenance"]

    lines: list[str] = []
    add = lines.append
    add(BEGIN)
    add("<!-- Generated by scripts/render_readme_numbers.py from "
        "results/final_run.json and the pytest collection count.")
    add("     Do not edit by hand. Regenerate: "
        "python scripts/render_readme_numbers.py --write")
    add("     CI verifies: python scripts/render_readme_numbers.py --check -->")
    add("")
    add(
        "> **The intervention demonstrably works &mdash; recovery-rate uplift is "
        f"{d6(cl['incremental_uplift_pp'])} pp with a Newcombe&nbsp;1998 95% "
        f"confidence interval of [{d6(ci['low_pp'])}, {d6(ci['high_pp'])}] pp "
        "that excludes zero &mdash; but it is not demonstrated to pay: net "
        f"incremental expected value is Rs&nbsp;{inr(cl['net_incremental_ev_inr'])} "
        f"with a stratified-bootstrap 95% interval of [{net['low']:.2f}, "
        f"{net['high']:.2f}] that crosses zero, so this project establishes that "
        "the system works, not that it pays.**")
    add("")
    add("| Claim | Figure | Reads as |")
    add("|---|---|---|")
    add(
        f"| Recovery-rate uplift (count basis) | **{d6(cl['incremental_uplift_pp'])} pp** "
        f"= {pct(cl['recovery_rate_treatment'])}% &minus; "
        f"{pct(cl['recovery_rate_control'])}% "
        f"({cl['recovery_count_treatment']}/{cl['n_treatment_customers']} vs "
        f"{cl['recovery_count_control']}/{cl['n_control_customers']}) | "
        f"&asymp; {cl['incremental_recoveries_count']:.0f} extra recoveries |"
    )
    add(
        f"| 95% CI on the uplift (Newcombe 1998 hybrid, Wilson-on-difference) | "
        f"**[{d6(ci['low_pp'])}, {d6(ci['high_pp'])}] pp** | "
        f"excludes zero &rarr; the effect is real |"
    )
    add(
        f"| Net incremental EV (value-weighted, counterfactual-subtracted, "
        f"minus Rs {inr(el['total_action_cost_inr'])} action cost) | "
        f"**Rs {inr(cl['net_incremental_ev_inr'])}** | point estimate only |"
    )
    add(
        f"| 95% CI on net incremental EV (seeded stratified bootstrap, "
        f"{net['n_resamples']:,} resamples) | "
        f"**[{net['low']:.2f}, {net['high']:.2f}]** | "
        f"**crosses zero &rarr; the value case is not established** |"
    )
    add(
        f"| Incremental recovered value, before action cost | "
        f"Rs {inr(cl['incremental_recovered_value_inr'])}, 95% bootstrap "
        f"[{gross['low']:.2f}, {gross['high']:.2f}] | also crosses zero |"
    )
    add(
        f"| Arms (customers) | {cl['n_treatment_customers']:,} treatment / "
        f"{cl['n_control_customers']:,} control of {cl['n_customers']:,} "
        f"({cl['n_treatment_blocked_customers']} guardrail-blocked) | "
        f"70:30 split, hashed on customer_id |"
    )
    add(
        f"| Actions actually taken | "
        f"{el['distinct_actions_by_rung'].get('email', 0):,} email nudges "
        f"({el['action_counts_by_rung'].get('email', 0):,} across events); "
        f"{el['route_to_human_count']} routed to a human, "
        f"{el['suppressed_by_guardrail_count']} guardrail-suppressed | "
        f"the ladder collapsed to one rung on this corpus |"
    )
    add("")
    add(
        f"Corpus: {prov['n_events']:,} events, {prov['n_customers']:,} customers, "
        f"seed {prov['rng_seed']}, policy {prov['policy_version']}, "
        f"window {prov['corpus_time_min']} &hellip; {prov['corpus_time_max']}. "
        f"Test suite: **{n_tests} tests** (`pytest -q`)."
    )
    add(END)
    return "\n".join(lines)


# ------------------------------------------------------- ARCHITECTURE block
def render_arch_block(n_tests: int) -> str:
    final = json.loads(FINAL.read_text(encoding="utf-8"))
    cl = final["aggregate"]["customer_level"]
    el = final["aggregate"]["event_level"]
    prov = final["provenance"]

    n_events = prov["n_events"]
    n_customers = prov["n_customers"]
    n_decisions = n_customers                       # one decision per customer
    n_act = el["distinct_actions_by_rung"].get("email", 0)
    # every ACT walks the (email-only) ladder -> exactly 7 guardrail rows each
    n_guardrail_rows = n_act * 7
    multi = final["aggregate"]["multi_failure_customers"]

    lines: list[str] = []
    add = lines.append
    add(BEGIN)
    add("<!-- Generated by scripts/render_readme_numbers.py from "
        "results/final_run.json and the pytest collection count.")
    add("     Do not edit by hand. Regenerate: "
        "python scripts/render_readme_numbers.py --write")
    add("     CI verifies: python scripts/render_readme_numbers.py --check -->")
    add("")
    add(
        f"On the frozen corpus the flow reduces to: **{n_events:,} webhook "
        f"events &rarr; {n_customers:,} normalized customers "
        f"({multi} with more than one failure) &rarr; {n_decisions:,} recorded "
        f"decisions** (`process_failure` is idempotent per `payment_id`), of "
        f"which **{n_act:,} reached ACT** and walked the guardrail ladder, "
        f"writing **{n_guardrail_rows:,} `guardrail_evaluations` rows** "
        f"(7 per rung attempted, never collapsed). "
        f"Arm assignment splits those {n_customers:,} customers "
        f"{cl['n_treatment_customers']:,} treatment / "
        f"{cl['n_control_customers']:,} control. The whole path is exercised by "
        f"**{n_tests} tests** (`pytest -q`)."
    )
    add(END)
    return "\n".join(lines)


# ---------------------------------------------------------------- splice/check
def block_in(text: str) -> str | None:
    i = text.find(BEGIN)
    j = text.find(END)
    if i == -1 or j == -1 or j < i:
        return None
    return text[i:j + len(END)]


def _targets():
    n_tests = test_count()
    return [
        (README, render_readme_block()),
        (EVALUATION, render_eval_block(n_tests)),
        (ARCHITECTURE, render_arch_block(n_tests)),
    ]


def do_write() -> int:
    changed = 0
    for path, fresh in _targets():
        if not path.exists():
            raise SystemExit(f"STOP: {path.name} does not exist.")
        text = path.read_text(encoding="utf-8")
        cur = block_in(text)
        if cur is None:
            raise SystemExit(
                f"STOP: {path.name} has no `{BEGIN}` / `{END}` marker pair. "
                "Add the markers once, then re-run --write."
            )
        if cur == fresh:
            print(f"{path.name}: already up to date.")
            continue
        path.write_text(text.replace(cur, fresh), encoding="utf-8", newline="\n")
        print(f"{path.name}: generated-numbers block rewritten.")
        changed += 1
    print(f"{changed} doc(s) rewritten." if changed else "All docs up to date.")
    return 0


def do_check() -> int:
    rc = 0
    for path, fresh in _targets():
        if not path.exists():
            print(f"FAIL: {path.name} does not exist.", file=sys.stderr)
            rc = 1
            continue
        cur = block_in(path.read_text(encoding="utf-8"))
        if cur is None:
            print(f"FAIL: {path.name} has no `{BEGIN}` / `{END}` marker pair.",
                  file=sys.stderr)
            rc = 1
            continue
        if cur == fresh:
            print(f"OK: {path.name} generated numbers match source.")
            continue
        rc = 1
        print(
            f"FAIL: {path.name} generated numbers drifted from source.\n"
            "Run: python scripts/render_readme_numbers.py --write\n",
            file=sys.stderr,
        )
        sys.stderr.writelines(difflib.unified_diff(
            cur.splitlines(keepends=True), fresh.splitlines(keepends=True),
            fromfile=f"{path.name} (committed)", tofile="rendered from source",
        ))
    return rc


def main(argv=None) -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--check", action="store_true",
                   help="verify every doc matches source (default)")
    g.add_argument("--write", action="store_true",
                   help="rewrite the generated blocks from source")
    args = ap.parse_args(argv)
    rc = do_write() if args.write else do_check()
    raise SystemExit(rc)


if __name__ == "__main__":
    main()
