"""Slice 11 -- render the headline numbers from the frozen corpus artifacts
into README.md, between the generated-numbers markers.

Single source of truth: the two committed artifacts
  * results/final_run.json            (STEP 1, full 2,000-event run, locked 70:30)
  * results/split_comparison_500.json (STEP 2, first-500-customer split sweep)

This script INVENTS no numbers. Every value below is read straight from those
files and formatted with fixed precision so the output is byte-stable.

Modes
-----
  python scripts/render_readme_numbers.py            # --check (default)
  python scripts/render_readme_numbers.py --check    # exit 1 if README drifted
  python scripts/render_readme_numbers.py --write     # splice fresh block in

CI runs `--check`: it re-derives the block from the artifacts and fails the
build if what is committed in README.md between the markers differs by a single
byte. Regenerate with `--write` and commit README.md alongside the artifacts.
"""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
README = REPO / "README.md"
FINAL = REPO / "results" / "final_run.json"
SPLIT = REPO / "results" / "split_comparison_500.json"

BEGIN = "<!-- BEGIN GENERATED NUMBERS -->"
END = "<!-- END GENERATED NUMBERS -->"


# ------------------------------------------------------------------ formatting
def inr(x: float) -> str:
    """`479834.0` -> `479,834.00` (Indian-file uses plain thousands here)."""
    return f"{x:,.2f}"


def pp(x: float) -> str:
    """percentage-point value already in pp units -> 2 dp."""
    return f"{x:.2f}"


def pct(rate: float) -> str:
    """proportion in [0,1] -> percent, 2 dp."""
    return f"{rate * 100:.2f}"


def short_sha(h: str) -> str:
    return h[:8]


# --------------------------------------------------------------------- render
def render_block() -> str:
    final = json.loads(FINAL.read_text(encoding="utf-8"))
    split = json.loads(SPLIT.read_text(encoding="utf-8"))

    cl = final["aggregate"]["customer_level"]
    el = final["aggregate"]["event_level"]
    agg = final["aggregate"]
    ci = cl["uplift_ci_95"]
    prov = final["provenance"]

    distinct_email = el["distinct_actions_by_rung"].get("email", 0)
    event_email = el["action_counts_by_rung"].get("email", 0)
    ev_floor_skips = el["skip_counts_by_reason"].get("EV_BELOW_FLOOR", 0)
    skip_reasons_seen = ", ".join(sorted(el["skip_counts_by_reason"])) or "none"

    sp = split["splits"]
    s70 = sp["70:30"]["customer_level"]
    s90 = sp["90:10"]["customer_level"]

    lines: list[str] = []
    add = lines.append

    add(BEGIN)
    add(
        "<!-- Generated by scripts/render_readme_numbers.py from "
        "results/final_run.json and results/split_comparison_500.json."
    )
    add("     Do not edit by hand. Regenerate: "
        "python scripts/render_readme_numbers.py --write")
    add("     CI verifies: python scripts/render_readme_numbers.py --check -->")
    add("")
    add(f"> **{final['synthetic_provenance_note']}**")
    add("")
    add("**Full corpus — "
        f"{prov['n_events']:,} events, {prov['n_customers']:,} customers, "
        "locked 70:30 split. Real `pipeline.process_failure` (guardrail "
        "walk-down included).**")
    add("")
    add("| # | Headline | Value |")
    add("|---|----------|-------|")
    add(
        f"| 1 | Incremental uplift, count basis (treatment − control recovery "
        f"rate) | **{pp(cl['incremental_uplift_pp'])} pp** "
        f"({pct(cl['recovery_rate_treatment'])}% − "
        f"{pct(cl['recovery_rate_control'])}%), "
        f"≈ {cl['incremental_recoveries_count']:.0f} extra recoveries |"
    )
    add(
        f"| 2 | 95% CI on uplift — Wilson score on the difference "
        f"(Newcombe 1998 hybrid) | "
        f"**[{pp(ci['low_pp'])}, {pp(ci['high_pp'])}] pp**, "
        f"width {pp(ci['width_pp'])} pp |"
    )
    add(
        f"| 3 | Arm sizes (customers) | "
        f"**{cl['n_treatment_customers']:,} treatment / "
        f"{cl['n_control_customers']:,} control** of {cl['n_customers']:,} "
        f"({cl['n_treatment_blocked_customers']} guardrail-blocked) |"
    )
    add(
        f"| 4 | Distinct actions (unique payment_id per rung; process_failure "
        f"is idempotent) | **{distinct_email:,} email nudges** "
        f"({event_email:,} across events); {ev_floor_skips} EV-floor skips, "
        f"{el['route_to_human_count']} routed to human, "
        f"{el['suppressed_by_guardrail_count']} guardrail-suppressed "
        f"(skip reasons seen: {skip_reasons_seen}) |"
    )
    iv_ci = cl["incremental_value_per_treated_customer_ci_95"]
    net_ci = cl["net_incremental_ev_ci_95"]
    add(
        f"| 5 | Incremental recovered value, value-weighted (treatment "
        f"recovered − control rate × treatment headcount) | "
        f"**₹{inr(cl['incremental_recovered_value_inr'])}** "
        f"(₹{inr(cl['incremental_value_per_treated_customer_inr'])} per treated "
        f"customer, 95% bootstrap [₹{inr(iv_ci['low'])}, ₹{inr(iv_ci['high'])}]) |"
    )
    add(
        f"| 6 | Net incremental EV (row 5 − ₹{inr(el['total_action_cost_inr'])} "
        f"distinct action cost) | "
        f"**₹{inr(cl['net_incremental_ev_inr'])}**, 95% bootstrap "
        f"[₹{inr(net_ci['low'])}, ₹{inr(net_ci['high'])}] |"
    )
    add("")
    if net_ci["low"] <= 0.0:
        add(
            f"**The row-6 lower bound is ₹{inr(net_ci['low'])} — at or below "
            "zero.** On this corpus the value-weighted incremental EV is not "
            "distinguishable from zero at 95% (seeded stratified bootstrap, "
            f"{net_ci['n_resamples']:,} resamples). The count-basis uplift "
            "(row 1) stays significant; the value-basis figure does not. Treat "
            "the ₹ point estimates as directional, not bankable."
        )
        add("")
    add(
        "Rows 5–6 are both on the treated-customer basis "
        f"({cl['n_treatment_customers']:,} customers); "
        f"{agg['multi_failure_customers']} customers have more than one event, "
        "which is why distinct actions (row 4) sit below the event count."
    )
    add("")
    add(f"**Count basis vs value basis.** {cl['value_vs_count_note']}")
    add("")
    add(f"**Policy selectivity.** {final['policy_selectivity_note']}")
    add("")
    add(
        "**Sensitivity — first "
        f"{split['n_customers_in_slice']} customers "
        f"({split['n_events_in_slice']} events), treatment-fraction sweep. "
        "`decide_with_ladder` direct, cross-checked against "
        "`eval.measurement.run_policy`.**"
    )
    add("")
    add("| Split | Treatment / control customers | Uplift | "
        "95% CI width (Wilson-on-difference) |")
    add("|-------|-------------------------------|--------|"
        "------------------------------------|")
    add(
        f"| 70:30 (locked) | {s70['n_treatment_customers']} / "
        f"{s70['n_control_customers']} | {pp(s70['incremental_uplift_pp'])} pp | "
        f"{pp(s70['uplift_ci_95']['width_pp'])} pp |"
    )
    add(
        f"| 90:10 | {s90['n_treatment_customers']} / "
        f"{s90['n_control_customers']} | {pp(s90['incremental_uplift_pp'])} pp | "
        f"{pp(s90['uplift_ci_95']['width_pp'])} pp |"
    )
    add("")
    add(f"Reading: {split['reading']}")
    add("")
    add(
        "Provenance (the commit that carries this artifact is the rest of it; "
        "hashes are over newline-normalized content, not raw bytes): "
        "events.json `" + short_sha(prov["sha256_events_json_normalized"]) + "`, "
        "ground_truth.json `"
        + short_sha(prov["sha256_ground_truth_json_normalized"]) + "`, "
        "decision_policy.json `"
        + short_sha(prov["sha256_decision_policy_json_normalized"]) + "`, "
        "seed " + str(prov["rng_seed"]) + ", corpus "
        + prov["corpus_time_min"] + " … " + prov["corpus_time_max"] + "."
    )
    add(END)
    return "\n".join(lines)


# ---------------------------------------------------------------- splice/check
def current_block(readme_text: str) -> str | None:
    i = readme_text.find(BEGIN)
    j = readme_text.find(END)
    if i == -1 or j == -1 or j < i:
        return None
    return readme_text[i:j + len(END)]


def do_write() -> int:
    text = README.read_text(encoding="utf-8")
    fresh = render_block()
    cur = current_block(text)
    if cur is None:
        raise SystemExit(
            f"STOP: {README.name} has no `{BEGIN}` / `{END}` marker pair. "
            "Add the markers once, then re-run --write."
        )
    if cur == fresh:
        print("README.md already up to date.")
        return 0
    README.write_text(text.replace(cur, fresh), encoding="utf-8", newline="\n")
    print("README.md generated-numbers block rewritten.")
    return 0


def do_check() -> int:
    text = README.read_text(encoding="utf-8")
    fresh = render_block()
    cur = current_block(text)
    if cur is None:
        print(
            f"FAIL: {README.name} has no `{BEGIN}` / `{END}` marker pair.",
            file=sys.stderr,
        )
        return 1
    if cur == fresh:
        print("OK: README.md generated numbers match the frozen artifacts.")
        return 0
    print(
        "FAIL: README.md generated numbers drifted from the artifacts.\n"
        "Run: python scripts/render_readme_numbers.py --write\n",
        file=sys.stderr,
    )
    diff = difflib.unified_diff(
        cur.splitlines(keepends=True),
        fresh.splitlines(keepends=True),
        fromfile="README.md (committed)",
        tofile="rendered from artifacts",
    )
    sys.stderr.writelines(diff)
    return 1


def main(argv=None) -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--check", action="store_true",
                   help="verify README matches the artifacts (default)")
    g.add_argument("--write", action="store_true",
                   help="rewrite the README block from the artifacts")
    args = ap.parse_args(argv)
    rc = do_write() if args.write else do_check()
    raise SystemExit(rc)


if __name__ == "__main__":
    main()
